#!/bin/bash
# Final solution - use webhook mode or create new bot

echo "================================"
echo "🔍 Bot Conflict Resolution"
echo "================================"
echo ""

# Stop the container since it's conflicting
docker compose stop mimerc-telegram

echo "The bot token is being used by another instance."
echo ""
echo "================================"
echo "SOLUTION OPTIONS:"
echo "================================"
echo ""
echo "Option 1: Create a NEW bot (Recommended)"
echo "-----------------------------------------"
echo "1. Open Telegram and message @BotFather"
echo "2. Send: /newbot"
echo "3. Name it: MiMerc Grocery Bot Fixed"
echo "4. Username: mimerc_fixed_bot (or similar)"
echo "5. Copy the new token"
echo "6. Update .env file with new token"
echo "7. Run: docker compose build mimerc-telegram"
echo "8. Run: docker compose up -d mimerc-telegram"
echo ""
echo "Option 2: Find the conflicting instance"
echo "----------------------------------------"
echo "Check if you have:"
echo "• The bot running on another computer"
echo "• A cloud deployment (Railway, Render, Heroku, etc.)"
echo "• An old Docker container on another machine"
echo "• Someone else using your token (it was in your .env)"
echo ""
echo "Option 3: Wait and retry"
echo "------------------------"
echo "Sometimes Telegram takes time to release a token."
echo "Wait 5-10 minutes and try again."
echo ""
echo "================================"
echo "YOUR BOT TOKEN MAY BE COMPROMISED"
echo "================================"
echo "Your token was visible in the .env file."
echo "Someone else might be using it."
echo "Creating a new bot is the safest option!"
